blank_issues_enabled: false
contact_links:
  - name: Terretacode.new related issues
    url: https://github.com/stackblitz/Terretacode.new/issues/new/choose
    about: Report issues related to Terretacode.new (not Terretacode.diy)
  - name: Chat
    url: https://thinktank.ottomator.ai
    about: Ask questions and discuss with other Terretacode.diy users.
